AWSTemplateFormatVersion: 2010-09-09
Description: VPC

Resources:
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
# VPCの作成
VPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 10.0.0.0/16
    EnableDnsSupport: true
    EnableDnsHostnames: true
    InstanceTenancy: default
    Tags:
      - Key: name
        Value: Sample-VPC
